<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/MasterPage.master" AutoEventWireup="true" CodeFile="Admin.aspx.cs" Inherits="Admin_Default" %>

<%-- Add content controls here --%>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="clearfix"></div>
		<!-- //w3_agileits_top_nav-->
		<!-- /inner_content-->
				<div class="inner_content">
				    <!-- /inner_content_w3_agile_info-->
					<div class="inner_content_w3_agile_info">
					<!-- /agile_top_w3_grids-->
					   <div class="agile_top_w3_grids">
					          <ul class="ca-menu">
									<li>
										<a href="../Admin/Buyer_Users.aspx">
											
											<i class="fa fa-building-o" aria-hidden="true"></i>
											<div class="ca-content">
												<h4 class="ca-main">
                                                    <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label></h4>
												<h3 class="ca-sub">Users</h3>
											</div>
										</a>
									</li>
									<li>
										<a href="#">
										  <i class="fa fa-user" aria-hidden="true"></i>
											<div class="ca-content">
												<h4 class="ca-main one"><asp:Label ID="Label2" runat="server" Text="Label"></asp:Label></h4>
												<h3 class="ca-sub one">Spare Parts</h3>
											</div>
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-database" aria-hidden="true"></i>
											<div class="ca-content">
											<h4 class="ca-main two">29,008</h4>
												<h3 class="ca-sub two">Visitors</h3>
											</div>
										</a>
									</li>
									<li>
										<a href="#">
											<i class="fa fa-tasks" aria-hidden="true"></i>
											<div class="ca-content">
												<h4 class="ca-main one"><asp:Label ID="Label3" runat="server" Text="Label"></asp:Label></h4>												
												<h3 class="ca-sub three">Cars Info</h3>
											</div>
										</a>
									</li>
										<li>
										<a href="#">
											<i class="fa fa-clone" aria-hidden="true"></i>
											<div class="ca-content">
												<h4 class="ca-main four">30,808</h4>
												<h3 class="ca-sub four">----</h3>
											</div>
										</a>
									</li>
									<div class="clearfix"></div>
								</ul>
					   </div>
					 <!-- //agile_top_w3_grids-->
				
				    </div>
					<!-- //inner_content_w3_agile_info-->
				</div>
		<!-- //inner_content-->
	

    <center>

    <div>
        <h1>Users Details</h1>
        <br>
    </div>
        <div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="id"  DataSourceID="SqlDataSource2" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" Height="400px" Width="1051px" >
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                <asp:BoundField DataField="First_name" HeaderText="First_name" SortExpression="First_name" />
                <asp:BoundField DataField="Last_name" HeaderText="Last_name" SortExpression="Last_name" />
                <asp:BoundField DataField="Username" HeaderText="Username" SortExpression="Username" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="Utype" HeaderText="Utype" SortExpression="Utype" />
                <asp:BoundField DataField="code" HeaderText="code" SortExpression="code" />
                <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />
                <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                <asp:BoundField DataField="state" HeaderText="state" SortExpression="state" />
                <asp:BoundField DataField="pincode" HeaderText="pincode" SortExpression="pincode" />
                <asp:BoundField DataField="phone_no" HeaderText="phone_no" SortExpression="phone_no" />
                <asp:BoundField DataField="profile_pic" HeaderText="profile_pic" SortExpression="profile_pic" />
            </Columns>
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" DeleteCommand="DELETE FROM [Registrationtb] WHERE [id] = @original_id" InsertCommand="INSERT INTO [Registrationtb] ([First_name], [Last_name], [Username], [Email], [Password], [Utype], [code], [address], [city], [state], [pincode], [phone_no], [profile_pic]) VALUES (@First_name, @Last_name, @Username, @Email, @Password, @Utype, @code, @address, @city, @state, @pincode, @phone_no, @profile_pic)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Registrationtb]" UpdateCommand="UPDATE [Registrationtb] SET [First_name] = @First_name, [Last_name] = @Last_name, [Username] = @Username, [Email] = @Email, [Password] = @Password, [Utype] = @Utype, [code] = @code, [address] = @address, [city] = @city, [state] = @state, [pincode] = @pincode, [phone_no] = @phone_no, [profile_pic] = @profile_pic WHERE [id] = @original_id">
                <DeleteParameters>
                    <asp:Parameter Name="original_id" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="First_name" Type="String" />
                    <asp:Parameter Name="Last_name" Type="String" />
                    <asp:Parameter Name="Username" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Password" Type="String" />
                    <asp:Parameter Name="Utype" Type="String" />
                    <asp:Parameter Name="code" Type="String" />
                    <asp:Parameter Name="address" Type="String" />
                    <asp:Parameter Name="city" Type="String" />
                    <asp:Parameter Name="state" Type="String" />
                    <asp:Parameter Name="pincode" Type="Int32" />
                    <asp:Parameter Name="phone_no" Type="String" />
                    <asp:Parameter Name="profile_pic" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="First_name" Type="String" />
                    <asp:Parameter Name="Last_name" Type="String" />
                    <asp:Parameter Name="Username" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Password" Type="String" />
                    <asp:Parameter Name="Utype" Type="String" />
                    <asp:Parameter Name="code" Type="String" />
                    <asp:Parameter Name="address" Type="String" />
                    <asp:Parameter Name="city" Type="String" />
                    <asp:Parameter Name="state" Type="String" />
                    <asp:Parameter Name="pincode" Type="Int32" />
                    <asp:Parameter Name="phone_no" Type="String" />
                    <asp:Parameter Name="profile_pic" Type="String" />
                    <asp:Parameter Name="original_id" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
           
    </div>
   
    </center>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>


    <script src="../assets/js/bootstrap.min.js"></script>

   </asp:Content>